// lib/country-codes.ts — country calling codes (dial codes) for the phone field.
// Full list of 203 countries/territories. India (+91) is first (default).

export interface CountryCode {
  code: string;     // dial code with +, e.g. "+91"
  country: string;  // display name
  iso: string;      // ISO 3166-1 alpha-2 (lowercase), e.g. "in"
}

export const countryCodes: CountryCode[] = [
  { code: '+91', country: 'India', iso: 'in' },
  { code: '+93', country: 'Afghanistan', iso: 'af' },
  { code: '+355', country: 'Albania', iso: 'al' },
  { code: '+213', country: 'Algeria', iso: 'dz' },
  { code: '+1', country: 'American Samoa', iso: 'as' },
  { code: '+376', country: 'Andorra', iso: 'ad' },
  { code: '+244', country: 'Angola', iso: 'ao' },
  { code: '+1', country: 'Anguilla', iso: 'ai' },
  { code: '+1', country: 'Antigua and Barbuda', iso: 'ag' },
  { code: '+54', country: 'Argentina', iso: 'ar' },
  { code: '+374', country: 'Armenia', iso: 'am' },
  { code: '+297', country: 'Aruba', iso: 'aw' },
  { code: '+61', country: 'Australia', iso: 'au' },
  { code: '+43', country: 'Austria', iso: 'at' },
  { code: '+994', country: 'Azerbaijan', iso: 'az' },
  { code: '+1', country: 'Bahamas', iso: 'bs' },
  { code: '+973', country: 'Bahrain', iso: 'bh' },
  { code: '+880', country: 'Bangladesh', iso: 'bd' },
  { code: '+1', country: 'Barbados', iso: 'bb' },
  { code: '+375', country: 'Belarus', iso: 'by' },
  { code: '+32', country: 'Belgium', iso: 'be' },
  { code: '+501', country: 'Belize', iso: 'bz' },
  { code: '+229', country: 'Benin', iso: 'bj' },
  { code: '+1', country: 'Bermuda', iso: 'bm' },
  { code: '+975', country: 'Bhutan', iso: 'bt' },
  { code: '+591', country: 'Bolivia', iso: 'bo' },
  { code: '+387', country: 'Bosnia and Herzegovina', iso: 'ba' },
  { code: '+267', country: 'Botswana', iso: 'bw' },
  { code: '+55', country: 'Brazil', iso: 'br' },
  { code: '+673', country: 'Brunei', iso: 'bn' },
  { code: '+359', country: 'Bulgaria', iso: 'bg' },
  { code: '+226', country: 'Burkina Faso', iso: 'bf' },
  { code: '+257', country: 'Burundi', iso: 'bi' },
  { code: '+855', country: 'Cambodia', iso: 'kh' },
  { code: '+237', country: 'Cameroon', iso: 'cm' },
  { code: '+1', country: 'Canada', iso: 'ca' },
  { code: '+238', country: 'Cape Verde', iso: 'cv' },
  { code: '+1', country: 'Cayman Islands', iso: 'ky' },
  { code: '+236', country: 'Central African Republic', iso: 'cf' },
  { code: '+235', country: 'Chad', iso: 'td' },
  { code: '+56', country: 'Chile', iso: 'cl' },
  { code: '+86', country: 'China', iso: 'cn' },
  { code: '+57', country: 'Colombia', iso: 'co' },
  { code: '+269', country: 'Comoros', iso: 'km' },
  { code: '+242', country: 'Congo', iso: 'cg' },
  { code: '+243', country: 'Congo (DRC)', iso: 'cd' },
  { code: '+682', country: 'Cook Islands', iso: 'ck' },
  { code: '+506', country: 'Costa Rica', iso: 'cr' },
  { code: '+385', country: 'Croatia', iso: 'hr' },
  { code: '+53', country: 'Cuba', iso: 'cu' },
  { code: '+357', country: 'Cyprus', iso: 'cy' },
  { code: '+420', country: 'Czech Republic', iso: 'cz' },
  { code: '+45', country: 'Denmark', iso: 'dk' },
  { code: '+253', country: 'Djibouti', iso: 'dj' },
  { code: '+1', country: 'Dominica', iso: 'dm' },
  { code: '+1', country: 'Dominican Republic', iso: 'do' },
  { code: '+593', country: 'Ecuador', iso: 'ec' },
  { code: '+20', country: 'Egypt', iso: 'eg' },
  { code: '+503', country: 'El Salvador', iso: 'sv' },
  { code: '+240', country: 'Equatorial Guinea', iso: 'gq' },
  { code: '+291', country: 'Eritrea', iso: 'er' },
  { code: '+372', country: 'Estonia', iso: 'ee' },
  { code: '+251', country: 'Ethiopia', iso: 'et' },
  { code: '+679', country: 'Fiji', iso: 'fj' },
  { code: '+358', country: 'Finland', iso: 'fi' },
  { code: '+33', country: 'France', iso: 'fr' },
  { code: '+689', country: 'French Polynesia', iso: 'pf' },
  { code: '+241', country: 'Gabon', iso: 'ga' },
  { code: '+220', country: 'Gambia', iso: 'gm' },
  { code: '+995', country: 'Georgia', iso: 'ge' },
  { code: '+49', country: 'Germany', iso: 'de' },
  { code: '+233', country: 'Ghana', iso: 'gh' },
  { code: '+350', country: 'Gibraltar', iso: 'gi' },
  { code: '+30', country: 'Greece', iso: 'gr' },
  { code: '+299', country: 'Greenland', iso: 'gl' },
  { code: '+1', country: 'Grenada', iso: 'gd' },
  { code: '+502', country: 'Guatemala', iso: 'gt' },
  { code: '+224', country: 'Guinea', iso: 'gn' },
  { code: '+245', country: 'Guinea-Bissau', iso: 'gw' },
  { code: '+592', country: 'Guyana', iso: 'gy' },
  { code: '+509', country: 'Haiti', iso: 'ht' },
  { code: '+504', country: 'Honduras', iso: 'hn' },
  { code: '+852', country: 'Hong Kong', iso: 'hk' },
  { code: '+36', country: 'Hungary', iso: 'hu' },
  { code: '+354', country: 'Iceland', iso: 'is' },
  { code: '+62', country: 'Indonesia', iso: 'id' },
  { code: '+98', country: 'Iran', iso: 'ir' },
  { code: '+964', country: 'Iraq', iso: 'iq' },
  { code: '+353', country: 'Ireland', iso: 'ie' },
  { code: '+972', country: 'Israel', iso: 'il' },
  { code: '+39', country: 'Italy', iso: 'it' },
  { code: '+225', country: 'Ivory Coast', iso: 'ci' },
  { code: '+1', country: 'Jamaica', iso: 'jm' },
  { code: '+81', country: 'Japan', iso: 'jp' },
  { code: '+962', country: 'Jordan', iso: 'jo' },
  { code: '+7', country: 'Kazakhstan', iso: 'kz' },
  { code: '+254', country: 'Kenya', iso: 'ke' },
  { code: '+686', country: 'Kiribati', iso: 'ki' },
  { code: '+965', country: 'Kuwait', iso: 'kw' },
  { code: '+996', country: 'Kyrgyzstan', iso: 'kg' },
  { code: '+856', country: 'Laos', iso: 'la' },
  { code: '+371', country: 'Latvia', iso: 'lv' },
  { code: '+961', country: 'Lebanon', iso: 'lb' },
  { code: '+266', country: 'Lesotho', iso: 'ls' },
  { code: '+231', country: 'Liberia', iso: 'lr' },
  { code: '+218', country: 'Libya', iso: 'ly' },
  { code: '+423', country: 'Liechtenstein', iso: 'li' },
  { code: '+370', country: 'Lithuania', iso: 'lt' },
  { code: '+352', country: 'Luxembourg', iso: 'lu' },
  { code: '+853', country: 'Macau', iso: 'mo' },
  { code: '+389', country: 'North Macedonia', iso: 'mk' },
  { code: '+261', country: 'Madagascar', iso: 'mg' },
  { code: '+265', country: 'Malawi', iso: 'mw' },
  { code: '+60', country: 'Malaysia', iso: 'my' },
  { code: '+960', country: 'Maldives', iso: 'mv' },
  { code: '+223', country: 'Mali', iso: 'ml' },
  { code: '+356', country: 'Malta', iso: 'mt' },
  { code: '+692', country: 'Marshall Islands', iso: 'mh' },
  { code: '+222', country: 'Mauritania', iso: 'mr' },
  { code: '+230', country: 'Mauritius', iso: 'mu' },
  { code: '+52', country: 'Mexico', iso: 'mx' },
  { code: '+691', country: 'Micronesia', iso: 'fm' },
  { code: '+373', country: 'Moldova', iso: 'md' },
  { code: '+377', country: 'Monaco', iso: 'mc' },
  { code: '+976', country: 'Mongolia', iso: 'mn' },
  { code: '+382', country: 'Montenegro', iso: 'me' },
  { code: '+212', country: 'Morocco', iso: 'ma' },
  { code: '+258', country: 'Mozambique', iso: 'mz' },
  { code: '+95', country: 'Myanmar', iso: 'mm' },
  { code: '+264', country: 'Namibia', iso: 'na' },
  { code: '+674', country: 'Nauru', iso: 'nr' },
  { code: '+977', country: 'Nepal', iso: 'np' },
  { code: '+31', country: 'Netherlands', iso: 'nl' },
  { code: '+64', country: 'New Zealand', iso: 'nz' },
  { code: '+505', country: 'Nicaragua', iso: 'ni' },
  { code: '+227', country: 'Niger', iso: 'ne' },
  { code: '+234', country: 'Nigeria', iso: 'ng' },
  { code: '+850', country: 'North Korea', iso: 'kp' },
  { code: '+47', country: 'Norway', iso: 'no' },
  { code: '+968', country: 'Oman', iso: 'om' },
  { code: '+92', country: 'Pakistan', iso: 'pk' },
  { code: '+680', country: 'Palau', iso: 'pw' },
  { code: '+507', country: 'Panama', iso: 'pa' },
  { code: '+675', country: 'Papua New Guinea', iso: 'pg' },
  { code: '+595', country: 'Paraguay', iso: 'py' },
  { code: '+51', country: 'Peru', iso: 'pe' },
  { code: '+63', country: 'Philippines', iso: 'ph' },
  { code: '+48', country: 'Poland', iso: 'pl' },
  { code: '+351', country: 'Portugal', iso: 'pt' },
  { code: '+974', country: 'Qatar', iso: 'qa' },
  { code: '+40', country: 'Romania', iso: 'ro' },
  { code: '+7', country: 'Russia', iso: 'ru' },
  { code: '+250', country: 'Rwanda', iso: 'rw' },
  { code: '+685', country: 'Samoa', iso: 'ws' },
  { code: '+378', country: 'San Marino', iso: 'sm' },
  { code: '+239', country: 'Sao Tome and Principe', iso: 'st' },
  { code: '+966', country: 'Saudi Arabia', iso: 'sa' },
  { code: '+221', country: 'Senegal', iso: 'sn' },
  { code: '+381', country: 'Serbia', iso: 'rs' },
  { code: '+248', country: 'Seychelles', iso: 'sc' },
  { code: '+232', country: 'Sierra Leone', iso: 'sl' },
  { code: '+65', country: 'Singapore', iso: 'sg' },
  { code: '+421', country: 'Slovakia', iso: 'sk' },
  { code: '+386', country: 'Slovenia', iso: 'si' },
  { code: '+677', country: 'Solomon Islands', iso: 'sb' },
  { code: '+252', country: 'Somalia', iso: 'so' },
  { code: '+27', country: 'South Africa', iso: 'za' },
  { code: '+82', country: 'South Korea', iso: 'kr' },
  { code: '+211', country: 'South Sudan', iso: 'ss' },
  { code: '+34', country: 'Spain', iso: 'es' },
  { code: '+94', country: 'Sri Lanka', iso: 'lk' },
  { code: '+249', country: 'Sudan', iso: 'sd' },
  { code: '+597', country: 'Suriname', iso: 'sr' },
  { code: '+268', country: 'Eswatini', iso: 'sz' },
  { code: '+46', country: 'Sweden', iso: 'se' },
  { code: '+41', country: 'Switzerland', iso: 'ch' },
  { code: '+963', country: 'Syria', iso: 'sy' },
  { code: '+886', country: 'Taiwan', iso: 'tw' },
  { code: '+992', country: 'Tajikistan', iso: 'tj' },
  { code: '+255', country: 'Tanzania', iso: 'tz' },
  { code: '+66', country: 'Thailand', iso: 'th' },
  { code: '+228', country: 'Togo', iso: 'tg' },
  { code: '+676', country: 'Tonga', iso: 'to' },
  { code: '+1', country: 'Trinidad and Tobago', iso: 'tt' },
  { code: '+216', country: 'Tunisia', iso: 'tn' },
  { code: '+90', country: 'Turkey', iso: 'tr' },
  { code: '+993', country: 'Turkmenistan', iso: 'tm' },
  { code: '+1', country: 'Turks and Caicos Islands', iso: 'tc' },
  { code: '+688', country: 'Tuvalu', iso: 'tv' },
  { code: '+256', country: 'Uganda', iso: 'ug' },
  { code: '+380', country: 'Ukraine', iso: 'ua' },
  { code: '+971', country: 'United Arab Emirates', iso: 'ae' },
  { code: '+44', country: 'United Kingdom', iso: 'gb' },
  { code: '+1', country: 'United States', iso: 'us' },
  { code: '+598', country: 'Uruguay', iso: 'uy' },
  { code: '+998', country: 'Uzbekistan', iso: 'uz' },
  { code: '+678', country: 'Vanuatu', iso: 'vu' },
  { code: '+379', country: 'Vatican City', iso: 'va' },
  { code: '+58', country: 'Venezuela', iso: 've' },
  { code: '+84', country: 'Vietnam', iso: 'vn' },
  { code: '+967', country: 'Yemen', iso: 'ye' },
  { code: '+260', country: 'Zambia', iso: 'zm' },
  { code: '+263', country: 'Zimbabwe', iso: 'zw' },
];

/** Sorted alphabetically by country name (India stays at index 0 as default). */
export const sortedCountryCodes: CountryCode[] = [
  countryCodes[0],
  ...countryCodes.slice(1).sort((a, b) => a.country.localeCompare(b.country)),
];

/** Default dial code — India. */
export const DEFAULT_DIAL_CODE = "+91";
